import { createContext, ReactNode, useContext, useMemo, useState } from 'react';

type Language = 'en' | 'sw';

type LanguageContextValue = {
  language: Language;
  setLanguage: (language: Language) => void;
  tr: (text: string) => string;
};

const sw: Record<string, string> = {
  Home: 'Nyumbani',
  Dashboard: 'Dashibodi',
  Alerts: 'Tahadhari',
  Profile: 'Wasifu',
  'Farmer Profile': 'Wasifu wa Mkulima',
  'App Version 1.0.0': 'Toleo la Programu 1.0.0',
  'Farm Profile': 'Wasifu wa Shamba',
  'Field Zones': 'Kanda za Shamba',
  'Crop Monitoring Schedule': 'Ratiba ya Ufuatiliaji wa Mazao',
  'Disease Alert Preferences': 'Mipangilio ya Tahadhari za Magonjwa',
  'Weather Units': 'Vipimo vya Hali ya Hewa',
  'Scan History': 'Historia ya Uchanganuzi',
  'Data Sync': 'Usawazishaji wa Data',
  'Privacy and Data': 'Faragha na Data',
  'Farmer Help and Support': 'Msaada kwa Mkulima',
  Logout: 'Toka',
  'Language Settings': 'Mipangilio ya Lugha',
  'Crop Agent': 'Wakala wa Mazao',
  'Animal Agent': 'Wakala wa Mifugo',
  'Application Updates': 'Masasisho ya Programu',
  'Current version: v1.0.0': 'Toleo la sasa: v1.0.0',
  'Last update: Security patch applied': 'Sasisho la mwisho: kiraka cha usalama kimewekwa',
  'Missed Notifications': 'Arifa Ulizokosa',
  'Leaf Rust risk rose to Medium': 'Hatari ya kutu ya majani imepanda hadi Kati',
  'Rainfall alert: heavy rain expected tomorrow': 'Tahadhari ya mvua: mvua kubwa inatarajiwa kesho',
  'Hi William!': 'Habari William!',
  'How can I help you today?': 'Ninawezaje kukusaidia leo?',
  'Ask anything...': 'Uliza chochote...',
  'Quick Actions': 'Vitendo vya Haraka',
  Scanning: 'Kuchanganua',
  'Scan crop or animal for early warning signs': 'Changanua zao au mnyama kwa dalili za mapema',
  'Upload Snapshot': 'Pakia Picha',
  'Upload photo for disease analysis': 'Pakia picha kwa uchambuzi wa ugonjwa',
  'Live Agent Monitoring': 'Ufuatiliaji wa Moja kwa Moja',
  'Other possibilities': 'Uwezekano mwingine',
  'Track active field checks in real-time': 'Fuatilia ukaguzi wa shamba kwa wakati halisi',
  'Overall Risk Level': 'Kiwango cha Hatari kwa Ujumla',
  Medium: 'Kati',
  'Last updated: Today': 'Imesasishwa mwisho: Leo',
  'Recent Alerts': 'Tahadhari za Hivi Karibuni',
  'View Details': 'Tazama Maelezo',
  'Alert Details': 'Maelezo ya Tahadhari',
  'Scan Information': 'Taarifa za Uchanganuzi',
  'Recommended Action': 'Hatua Inayopendekezwa',
  'Detected: ': 'Iligunduliwa: ',
  'Next check: ': 'Ukaguzi unaofuata: ',
  'Crop Disease Analysis': 'Uchambuzi wa Magonjwa ya Mazao',
  'Animal Health Analysis': 'Uchambuzi wa Afya ya Mifugo',
  Crop: 'Mazao',
  Animal: 'Mifugo',
  'Check View Scan History': 'Angalia Historia ya Uchanganuzi',
  'Farmer Actions': 'Hatua za Mkulima',
  'Choose Language': 'Chagua Lugha',
  'Select your preferred app language. Changes apply immediately.':
    'Chagua lugha unayopendelea. Mabadiliko yataonekana mara moja.',
  English: 'Kiingereza',
  Swahili: 'Kiswahili',
  Selected: 'Imechaguliwa',
  'Welcome back': 'Karibu tena',
  Email: 'Barua pepe',
  Password: 'Nenosiri',
  'Log In': 'Ingia',
  'Need an account? Sign Up': 'Unahitaji akaunti? Jisajili',
  'Create account': 'Fungua akaunti',
  'Full name': 'Jina kamili',
  'Sign Up': 'Jisajili',
  'Already registered? Log In': 'Umeshajisajili? Ingia',
  'Your Reliable AI Farm Assistant': 'Msaidizi wako wa kuaminika wa shamba wa AI',
  'Get started with me': 'Anza nami',
  "Don't have an account yet?": 'Huna akaunti bado?',
  'No chat history yet for this agent.': 'Bado hakuna historia ya mazungumzo kwa wakala huyu.',
  'Chat not found. Start from Home to create a new conversation.':
    'Mazungumzo hayajapatikana. Anza kutoka Nyumbani kuunda mazungumzo mapya.',
  'Welcome to Flora AI': 'Karibu Flora AI',
  'Use the top-left selector to switch between Crop Agent and Animal Agent.':
    'Tumia kichaguzi cha juu kushoto kubadili kati ya Wakala wa Mazao na Wakala wa Mifugo.',
  'Use Quick Actions': 'Tumia Vitendo vya Haraka',
  'Tap the plus button in the input area to scan, upload snapshots, or start live monitoring.':
    'Gusa kitufe cha kuongeza kwenye sehemu ya kuandika ili kuchanganua, kupakia picha, au kuanza ufuatiliaji wa moja kwa moja.',
  'Check Dashboard': 'Angalia Dashibodi',
  'Open Dashboard to view crop and animal analytics, risk levels, and recommended actions.':
    'Fungua Dashibodi kuona uchambuzi wa mazao na mifugo, viwango vya hatari, na hatua zinazopendekezwa.',
  'Review Alerts': 'Kagua Tahadhari',
  'Go to Alerts to track current risks and tap View Details for scan-based recommendations.':
    'Nenda Tahadhari kufuatilia hatari za sasa na gusa Tazama Maelezo kwa mapendekezo ya uchanganuzi.',
  'Manage Profile Settings': 'Dhibiti Mipangilio ya Wasifu',
  'Use Profile to manage farm settings, language, privacy, and support options.':
    'Tumia Wasifu kudhibiti mipangilio ya shamba, lugha, faragha, na chaguo za msaada.',
  Step: 'Hatua',
  of: 'ya',
  Back: 'Nyuma',
  Skip: 'Ruka',
  Next: 'Ifuatayo',
  Done: 'Imekamilika',
  'Select an image from your device for disease analysis.':
    'Chagua picha kutoka kwenye kifaa chako kwa uchambuzi wa ugonjwa.',
  'Choose Image': 'Chagua Picha',
  'Image ready and synced to analytics': 'Picha iko tayari na imesawazishwa kwenye uchambuzi',
  'Snapshot uploaded and analyzed. Dashboard and Alerts updated.':
    'Picha imepakiwa na kuchambuliwa. Dashibodi na Tahadhari zimesasishwa.',
  'Image picker is unavailable in this offline build. Install expo-image-picker to enable device uploads.':
    'Kiteuzi cha picha hakipatikani kwenye toleo hili la nje ya mtandao. Sakinisha expo-image-picker kuwezesha upakiaji kutoka kifaa.',
  'Media permission denied. Please allow photo access.':
    'Ruhusa ya media imekataliwa. Tafadhali ruhusu ufikiaji wa picha.',
  'Point camera at crop leaves/stem and keep it steady.':
    'Elekeza kamera kwenye majani/shina la zao na ushike vizuri.',
  'Point camera at the animal and keep it steady for health cues.':
    'Elekeza kamera kwa mnyama na ushike vizuri kwa viashiria vya afya.',
  'Analyze Current Frame': 'Changanua Fremu ya Sasa',
  'Analyzing': 'Inachambua',
  'Scan complete. Dashboard and Alerts have been updated.':
    'Uchanganuzi umekamilika. Dashibodi na Tahadhari zimesasishwa.',
  LIVE: 'MOJA KWA MOJA',
  PAUSED: 'IMESIMAMA',
  'Monitoring in progress. New analytics are being sent to Dashboard and Alerts.':
    'Ufuatiliaji unaendelea. Uchambuzi mpya unatumiwa kwenye Dashibodi na Tahadhari.',
  'Start monitoring to stream live field analysis updates.':
    'Anza ufuatiliaji ili kupokea masasisho ya moja kwa moja ya uchambuzi wa shamba.',
  'Updates sent:': 'Masasisho yaliyotumwa:',
  'Stop Monitoring': 'Simamisha Ufuatiliaji',
  'Start Monitoring': 'Anza Ufuatiliaji',
  'Open Dashboard': 'Fungua Dashibodi',
  'Open Alerts': 'Fungua Tahadhari',
  'Latest prediction': 'Utabiri wa mwisho',
  'Latest model result': 'Matokeo ya hivi punde ya modeli',
  'Analyzing image': 'Inachambua picha',
  'Extracting disease cues, confidence, and guidance...': 'Inatoa vidokezo vya ugonjwa, uaminifu, na mwongozo...',
  'Run a scan or upload a snapshot to see the latest result here.': 'Fanya uchanganuzi au pakia picha ili kuona matokeo ya hivi punde hapa.',
  'Why': 'Kwa nini',
  'Treatment': 'Matibabu',
  'Prevention': 'Kuzuia',
  'Maintain hygiene, nutrition, and scheduled health checks.': 'Dumisha usafi, lishe, na ukaguzi wa afya uliopangwa.',
  'Routine monitoring.': 'Ufuatiliaji wa kawaida.',
  'Prediction ready': 'Utabiri uko tayari',
  'Confidence': 'Uhakika',
  'Photo from gallery/camera': 'Picha kutoka galeria/kamera',
  'Open camera and analyze': 'Fungua kamera na uchanganue',
  'Photo captured and analyzed. Dashboard and Alerts updated.': 'Picha imepigwa na kuchambuliwa. Dashibodi na Tahadhari zimesasishwa.',
  'Permission needed': 'Ruhusa inahitajika',
  'Please allow photo access to choose an image.': 'Ruhusu ufikiaji wa picha ili kuchagua taswira.',
  'Please allow camera access to take a photo.': 'Ruhusu ufikiaji wa kamera ili kupiga picha.',
  'Camera permission denied. Please allow camera access.': 'Ruhusa ya kamera imekataliwa. Tafadhali ruhusu upatikanaji wa kamera.',
  'Camera unavailable': 'Kamera haipatikani',
  'No camera found on this device or emulator. Please try on a physical device.': 'Hakuna kamera imepatikana kwenye kifaa hiki au emulator. Jaribu kwenye kifaa halisi.',
  'Capture failed': 'Uchukuaji umeshindikana',
  'Capture failed. Please try again.': 'Upigaji picha umeshindikana. Tafadhali jaribu tena.',
  'Upload failed': 'Upakiaji umeshindikana',
  'Upload failed. Please try again.': 'Upakiaji umeshindikana. Tafadhali jaribu tena.',
  'Media permission denied. Please allow photo access.': 'Ruhusa ya midia imekataliwa. Tafadhali ruhusu ufikiaji wa picha.',
  'Analyzing image for disease': 'Inachambua picha kutafuta ugonjwa',
  'Choose what you want to do today.': 'Chagua unachotaka kufanya leo.',
  'Upload': 'Pakia',
  'Take Photo': 'Piga Picha',
  'Upload Snapshot': 'Pakia Picha',
  'Scan History': 'Historia ya Uchanganuzi',
  'Chat Sessions': 'Vipindi vya gumzo',
  'Agent History': 'Historia ya Wakala',
  'No scans yet for this agent.': 'Hakuna uchanganuzi bado kwa wakala huyu.',
  'All recent scans and classification results': 'Uchanganuzi na matokeo ya uainishaji ya hivi karibuni',
  'Animal Scan History': 'Historia ya Uchanganuzi wa Mifugo',
  'Crop Scan History': 'Historia ya Uchanganuzi wa Mazao',
  'Latest model result': 'Matokeo ya hivi punde ya modeli',
  'Model Confidence: ': 'Uhakika wa modeli: ',
  'Scan ID: ': 'Kitambulisho cha uchanganuzi: ',
  'Detected: ': 'Iligunduliwa: ',
  'Next check: ': 'Ukaguzi unaofuata: ',
  'Recommended Action': 'Hatua Inayopendekezwa',
  'Scan Information': 'Taarifa za Uchanganuzi',
  'Alert Details': 'Maelezo ya Tahadhari',
  'Recent Alerts': 'Tahadhari za Hivi Karibuni',
  'Overall Risk Level': 'Kiwango cha Hatari kwa Ujumla',
  'How to interpret risk levels': 'Jinsi ya kufasiri viwango vya hatari',
  'How to take high-quality crop photos': 'Jinsi ya kupiga picha za mazao zenye ubora',
  'How to submit disease feedback': 'Jinsi ya kutuma maoni ya ugonjwa',
  'Response Time': 'Muda wa Majibu',
  'Risk Threshold': 'Kizingiti cha Hatari',
  'Risk Mapping': 'Uchoraji wa Hatari',
  'Display Preferences': 'Mapendeleo ya Uonyeshaji',
  'Sync Status': 'Hali ya Usawazishaji',
  'Sync Rules': 'Kanuni za Usawazishaji',
  'Queued photos: 14': 'Picha kwenye foleni: 14',
  'Pending offline records: 6': 'Rekodi za nje ya mtandao zinazosubiri: 6',
  'Last successful sync: Today, 10:12 AM': 'Usawazishaji uliopita kufanikiwa: Leo, 10:12 AM',
  'Auto-sync on Wi-Fi: Enabled': 'Usawazishaji moja kwa moja kwenye Wi-Fi: Umewezeshwa',
  'Auto-sync on mobile data: Disabled': 'Usawazishaji kwenye data ya simu: Umezimwa',
  'Share anonymized scan data: Enabled': 'Shiriki data ya uchanganuzi isiyotambulika: Imewashwa',
  'Use feedback for model improvement: Enabled': 'Tumia maoni kuboresha modeli: Imewashwa',
  'Photo retention: 12 months': 'Hifadhi picha: miezi 12',
  'Data Retention': 'Uhifadhi Data',
  'You can request export or deletion of your records.': 'Unaweza kuomba kusafirishwa au kufutwa kwa rekodi zako.',
  'Scan history retention: 24 months': 'Uhifadhi wa historia ya uchanganuzi: miezi 24',
  'Data Sync': 'Usawazishaji wa Data',
  'Background sync: Enabled': 'Usawazishaji wa usuli: Umewezeshwa',
  'In-app notifications: Enabled': 'Arifa ndani ya programu: Zimewezeshwa',
  'Email: Disabled': 'Barua pepe: Imezimwa',
  'SMS: Enabled': 'SMS: Zimewezeshwa',
  'Email digest: Weekly summary': 'Muhtasari wa barua pepe: Muhtasari wa kila wiki',
  'Critical alerts will still be delivered during quiet hours.': 'Arifa muhimu zitatumwa hata wakati wa saa tulivu.',
  'Quiet Hours': 'Saa za Utulivu',
  '10:00 PM to 5:30 AM': '4:00 usiku hadi 11:30 asubuhi',
  'Reminder Channels': 'Njia za Vikumbusho',
  'Alert Channels': 'Njia za Tahadhari',
  'Current trigger: Medium and High risk': 'Kichocheo cha sasa: Hatari ya Kati na Juu',
  'Critical outbreak alerts: Always on': 'Arifa muhimu za mlipuko: Kila wakati',
  'Urgent disease alerts: Within 30 minutes': 'Arifa za haraka za ugonjwa: Ndani ya dakika 30',
  'General support tickets: Within 24 hours': 'Tiketi za msaada wa jumla: Ndani ya saa 24',
  'Response Time': 'Muda wa Majibu',
  'Location sharing for risk maps: Enabled': 'Kushiriki eneo kwa ramani za hatari: Kumewezeshwa',
  'Risk Mapping': 'Uchoraji wa Hatari',
  'Consent Settings': 'Mipangilio ya Ridhaa',
  'Active Schedules': 'Ratiba Zinazoendelea',
  'Registered Zones': 'Kanda Zilizorekodiwa',
  'Primary Crops': 'Mazao Makuu',
  'Zone A1 - Maize - 7.5 acres': 'Kanda A1 - Mahindi - ekari 7.5',
  'Zone A2 - Maize - 10.5 acres': 'Kanda A2 - Mahindi - ekari 10.5',
  'Zone B1 - Tomato - 8 acres': 'Kanda B1 - Nyanya - ekari 8',
  'Zone C1 - Cassava - 6.5 acres': 'Kanda C1 - Muhogo - ekari 6.5',
  'Maize (18 acres)': 'Mahindi (ekari 18)',
  'Tomato (8 acres)': 'Nyanya (ekari 8)',
  'Cassava (6.5 acres)': 'Muhogo (ekari 6.5)',
  'Maize Zones: Every 2 days at 7:00 AM': 'Kanda za Mahindi: Kila siku 2 saa 1:00 asubuhi',
  'Tomato Zones: Daily at 6:30 AM': 'Kanda za Nyanya: Kila siku saa 12:30 asubuhi',
  'Cassava Zones: Twice per week at 8:00 AM': 'Kanda za Muhogo: Mara mbili kwa wiki saa 2:00 asubuhi',
  'Total Acreage: 32.5 acres': 'Jumla ya ekari: 32.5',
  'Region: Northern District': 'Mkoa: Wilaya ya Kaskazini',
  'Owner: Sabrina Aryan': 'Mmiliki: Sabrina Aryan',
  'Profile Status': 'Hali ya Wasifu',
  'Account': 'Akaunti',
  'Profile': 'Wasifu',
  'Profile Status': 'Hali ya Wasifu',
  'Farm Details': 'Maelezo ya Shamba',
  'Farm Name: Green Valley Cooperative': 'Jina la Shamba: Green Valley Cooperative',
  'Primary Crops': 'Mazao Makuu',
  'Current Units': 'Vipimo vya Sasa',
  'Pressure: hPa': 'Shinikizo: hPa',
  'Rainfall: Millimeters (mm)': 'Mvua: Milimita (mm)',
  'Temperature: Celsius (C)': 'Joto: Selsiasi (°C)',
  'Wind Speed: km/h': 'Kasi ya Upepo: km/h',
  'Weather Units': 'Vipimo vya Hali ya Hewa',
  'Field Zones': 'Kanda za Shamba',
  'Registered Zones': 'Kanda Zilizorekodiwa',
  'Risk Mapping': 'Uchoraji wa Hatari',
  'Display Preferences': 'Mapendeleo ya Uonyeshaji',
  'Choose Image': 'Chagua Picha',
  'Select an image from your device for disease analysis.': 'Chagua picha kutoka kifaa chako kwa uchambuzi wa ugonjwa.',
  'Image ready and synced to analytics': 'Picha iko tayari na imesawazishwa kwenye uchambuzi',
  'Snapshot uploaded and analyzed. Dashboard and Alerts updated.': 'Picha imepakiwa na kuchambuliwa. Dashibodi na Tahadhari zimesasishwa.',
  'Analyze Current Frame': 'Changanua Fremu ya Sasa',
  'Scanning': 'Kuchanganua',
  'Open Quick Actions to scan, upload snapshots, or start live monitoring.': 'Fungua Vitendo vya Haraka kuchanganua, kupakia picha, au kuanza ufuatiliaji wa moja kwa moja.',
  'Open Dashboard to view crop and animal analytics, risk levels, and recommended actions.': 'Fungua Dashibodi kuona uchambuzi wa mazao na mifugo, viwango vya hatari, na hatua zinazopendekezwa.',
  'Use Quick Actions': 'Tumia Vitendo vya Haraka',
  'Use the top-left selector to switch between Crop Agent and Animal Agent.': 'Tumia kichaguzi cha juu kushoto kubadili kati ya Wakala wa Mazao na Wakala wa Mifugo.',
  'Monitor livestock health notes, environment warnings, and care recommendations.': 'Fuatilia maelezo ya afya ya mifugo, onyo la mazingira, na mapendekezo ya utunzaji.',
  'Chat with Agent': 'Zungumza na Wakala',
  'Ask anything...': 'Uliza chochote...',
  'Your AI-companion awaits': 'Msaidizi wako wa AI anakusubiri',
  'Your Smart AI farm Assistant': 'Msaidizi wako mahiri wa shamba wa AI',
  'Get Started': 'Anza',
  'LOGIN': 'INGIA',
  'SIGN UP': 'JISAJILI',
  'First Name': 'Jina la Kwanza',
  'Last Name': 'Jina la Mwisho',
  'Already have an account? Log In': 'Tayari una akaunti? Ingia',
  'Need an account? Sign Up': 'Unahitaji akaunti? Jisajili',
  'Already registered? Log In': 'Umesajiliwa tayari? Ingia',
  'Email': 'Barua pepe',
  'Password': 'Nenosiri',
  'Age (optional)': 'Umri (hiari)',
  'Your Reliable AI Farm Assistant': 'Msaidizi wako wa shamba wa AI wa kuaminika',
  'How can I help you today?': 'Ninawezaje kukusaidia leo?',
  'Open Alerts': 'Fungua Tahadhari',
  'Open Dashboard': 'Fungua Dashibodi',
  'Start monitoring to stream live field analysis updates.': 'Anza ufuatiliaji ili kupokea masasisho ya moja kwa moja ya uchambuzi wa shamba.',
  'Monitoring in progress. New analytics are being sent to Dashboard and Alerts.': 'Ufuatiliaji unaendelea. Uchambuzi mpya unatumiwa kwenye Dashibodi na Tahadhari.',
  'Updates sent:': 'Masasisho yaliyotumwa:',
  LIVE: 'MOJA KWA MOJA',
  PAUSED: 'IMESIMAMA',
  'Next recommended review: In 30 days': 'Mapitio yanayopendekezwa yafuatayo: Ndani ya siku 30',
  'Latest prediction': 'Utabiri wa mwisho',
  'Step': 'Hatua',
  of: 'ya',
  'Back': 'Nyuma',
  'Skip': 'Ruka',
  'Next': 'Ifuatayo',
  'Done': 'Imekamilika',
  'Recent Alerts': 'Tahadhari za Hivi Karibuni',
  'Alert Channels': 'Njia za Tahadhari',
  'Quiet Hours': 'Saa za Utulivu',
  'Open Dashboard to view crop and animal analytics, risk levels, and recommended actions.': 'Fungua Dashibodi kuona uchambuzi wa mazao na mifugo, viwango vya hatari, na hatua zinazopendekezwa.',
  'Go to Alerts to track current risks and tap View Details for scan-based recommendations.': 'Nenda Tahadhari kufuatilia hatari za sasa na gusa Tazama Maelezo kwa mapendekezo yanayotokana na uchanganuzi.',
  'Run a scan or upload a snapshot to see the latest result here.': 'Fanya uchanganuzi au pakia picha ili kuona matokeo ya hivi punde hapa.',
  'Latest model result': 'Matokeo ya hivi punde ya modeli',
  'Latest prediction': 'Utabiri wa mwisho',
  'Latest model result': 'Matokeo ya hivi punde ya modeli',
  'Latest prediction': 'Utabiri wa mwisho',
  'Affected Zone: ': 'Eneo lililoathiriwa: ',
  'Agent Animal Well Being': 'Wakala: Ustawi wa Mifugo',
  'Agent Settings': 'Mipangilio ya Wakala',
  'Agronomy Hotline: +1 (800) 555-0184': 'Simu ya Ushauri wa Kilimo: +1 (800) 555-0184',
  'Configure detection sensitivity, notification channels, and preferred intervention style.':
    'Sanidi unyeti wa kugundua, njia za arifa, na mtindo wa uingiliaji unaopendelea.',
  'Crop Type: ': 'Aina ya zao: ',
  'Daily weather summary: Enabled': 'Muhtasari wa hali ya hewa wa kila siku: Umewezeshwa',
  'Field Officer Desk: +1 (800) 555-0162': 'Ofisi ya Afisa Shamba: +1 (800) 555-0162',
  'Flora AI': 'Flora AI',
  'Flora AI!': 'Flora AI!',
  'High Risk: Zone A2': 'Hatari Kuu: Kanda A2',
  'In-app: Enabled': 'Ndani ya programu: Imewezeshwa',
  'Last updated: Today, 8:45 AM': 'Imesasishwa: Leo, 8:45 AM',
  'Low Risk: Zone C1': 'Hatari Ndogo: Kanda C1',
  'Medium Risk: Zone B1': 'Hatari ya Kati: Kanda B1',
  'Please try again.': 'Tafadhali jaribu tena.',
  'Quick Guides': 'Miongozo ya Haraka',
  'SMS reminders: Enabled': 'Vikumbusho vya SMS: Vimewezeshwa',
  'Sample: Animal health looks stable. Monitor temperature and isolate any weak animal.':
    'Mfano: Afya ya mnyama inaonekana thabiti. Fuatilia joto na utenganishe mnyama yeyote aliyedhoofika.',
  'Sample: I can help with disease risk, scan history, and treatment recommendations.':
    'Mfano: Naweza kusaidia na hatari ya ugonjwa, historia ya uchanganuzi, na mapendekezo ya matibabu.',
  'Sample: Leaf rust risk is medium. Re-scan in 48 hours and apply preventive fungicide.':
    'Mfano: Hatari ya kutu ya majani ni ya kati. Fanya uchanganuzi tena baada ya saa 48 na tumia kiua-kuvu cha kuzuia.',
  'Sample: Rain is expected tomorrow. Increase disease checks in wet field zones.':
    'Mfano: Mvua inatarajiwa kesho. Ongeza ukaguzi wa magonjwa katika maeneo yenye unyevunyevu.',
  Selected: 'Imechaguliwa',
  'Severe weather warnings: Enabled': 'Onyo za hali mbaya ya hewa: Zimewezeshwa',
  'Support Contacts': 'Nambari za Msaada',
  'Support Email: help@flora-ai.app': 'Barua pepe ya Msaada: help@flora-ai.app',
  'Swahili': 'Kiswahili',
  'of': 'ya',
  'Alerts': 'Tahadhari',
  'Animal': 'Mifugo',
  'Crop': 'Mazao',
  'Dashboard': 'Dashibodi',
  'English': 'Kiingereza',
  'Home': 'Nyumbani',
  'LIVE': 'MOJA KWA MOJA',
  'Medium': 'Kati',
  'PAUSED': 'IMESIMAMA',
  'Selected': 'Imechaguliwa',
};

const LanguageContext = createContext<LanguageContextValue | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>('en');

  const value = useMemo<LanguageContextValue>(
    () => ({
      language,
      setLanguage,
      tr: (text: string) => {
        if (language === 'en') return text;
        return sw[text] ?? text;
      },
    }),
    [language]
  );

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) throw new Error('useLanguage must be used within LanguageProvider');
  return context;
}
